<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12678" started-at="2014-03-06T11:59:22Z" finished-at="2014-03-06T11:59:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12678" started-at="2014-03-06T11:59:22Z" finished-at="2014-03-06T11:59:34Z">
      <class name="test.OpenStackTest">
        <test-method status="FAIL" signature="globalTest()[pri:0, instance:test.OpenStackTest@64633e5e]" name="globalTest" duration-ms="12662" started-at="2014-03-06T12:59:22Z" finished-at="2014-03-06T12:59:34Z">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Don't know how to write JSON of class java.lang.Class]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Don't know how to write JSON of class java.lang.Class
	at clojure.data.json$write_generic.invoke(json.clj:369)
	at clojure.data.json$fn__1650$G__1645__1657.invoke(json.clj:286)
	at clojure.data.json$write_object.invoke(json.clj:335)
	at clojure.data.json$fn__1650$G__1645__1657.invoke(json.clj:286)
	at clojure.data.json$write.doInvoke(json.clj:452)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:621)
	at clojure.data.json$write_str.doInvoke(json.clj:459)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at com.enterpriseweb.openstack.OpenStackAPI$_tokens.invoke(OpenStackAPI.clj:69)
	at com.enterpriseweb.openstack.OpenStackAPI.tokens(Unknown Source)
	at test.OpenStackTest.globalTest(OpenStackTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- globalTest -->
      </class> <!-- test.OpenStackTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
